#!/bin/busybox sh

export NLDIR="$PWD/prime/etc/nanolin.d"
export NLLOG="$PWD/work/nanolin.log"
export NLRLK="$PWD/work/lock"

export PKGDIR="$PWD/packages"
export PKGSRC="$PWD/work"
export PKGOUT="$PWD/work/out"

mkdir -p  "$NLRLK"

source $(dirname "$0")/prime/usr/bin/nanolin
