#!/bin/busybox sh

# add busybox links
/bin/busybox --install /bin

# make /dev/null always
mknod /dev/null c 1 3

# run any nanolin addons
/sbin/nanolin run init

# switch busybox init
exec /sbin/init
