#!/bin/sh

[ -n "$NLDBG" ] && echo "DEBUG: $0 $@"

# usage check 
[ -z "$1" ] && echo "$NLHDR
	Run action asynchronously.

    Usage:

	$NLCLI ${NLACT/./ } <action> [options]
" && exit 1

# run with locks and logging
"$NLBIN" $@ &
