#!/bin/sh

[ -n "$NLDBG" ] && echo "DEBUG: ${NLBIN##*/} ${0##*/} $@ - $0"

# usage check 
[ -z "$1" ] && echo "$NLHDR
	Run action asynchronously.

	Usage:

	${NLBIN##*/} async <action> [options]
" && exit 1

# run with locks and logging
"$NLBIN" $@ &
