#!/bin/sh

export NLMSG="${NLMSG:-Manage configuration options.}"
export NLUSE="${NLUSE:-${NLBIN##*/} ${0##*/} <actions> [options]}"
export NLCMD="${NLCMD:-$NLDIR/each}"
export NLARG="${NLARG:-$0.$1}"

[ -n "$NLDBG" ] && echo "DEBUG: ${NLBIN##*/} ${0##*/} $@ - $NLDIR/config"

[ -z "$1" ] && echo "$NLHDR
	$NLMSG

    Usage:

	$NLUSE

    Actions:

$("$NLBIN" indent command list ${0##*/})
" && exit

shift

# run command
"$NLCMD" "$NLARG" $@
