#!/bin/sh

export NLMSG="${NLMSG:-Manage configuration options.}"
export NLUSE="${NLUSE:-<actions> [options]}"
export NLCMD="${NLCMD:-$NLDIR/each}"
export NLARG="${NLARG:-${0##*/}.$1}"

[ -z "$1" ] && echo "$NLHDR
	$NLMSG

    Usage:

	$NLCLI ${NLACT/./ } $NLUSE

    Actions:

$("$NLBIN" indent command list ${0##*/})
" && exit

shift

[ -n "$NLDBG" ] && echo "DEBUG: $NLCMD $NLARG $@"

# run command
"$NLCMD" "$NLARG" $@
