#!/bin/sh

export NLMSG="${NLMSG:-Manage Configuration Options}"
export NLUSE="${NLUSE:-<actions> [options]}"
export NLCMD="${NLCMD:-$NLDIR/each}"
export NLARG="${NLARG:-${0##*/}.$1}"

[ -n "$NLDBG" ] && echo "DEBUG: $0 (config) $@"

[ -z "$1" ] && echo "$NLHDR
	$NLMSG

    Usage:

	$NLCLI ${NLACT/./ } $NLUSE

    Actions:

$(NLARG= "$NLBIN" indent command list ${0##*/})
" && exit 1

shift

[ -n "$NLDBG" ] && echo "DEBUG: exec $NLCMD $NLARG $@"

# run command
exec "$NLCMD" "$NLARG" $@
