#!/bin/sh

# check usage
[ -z "$1" ] && echo "$NLHDR
	Runs a script and its children

	Usage:
	
	${NLBIN##*/} each <action> [options]
" && exit

NLACT="${1##*/}"
NLWAIT=""

shift

# set aliases to shorten code
alias runexec="'$NLDIR'/$NLACT"
alias runlock="'$NLDIR'/lock"
alias logcall="'$NLDIR'/log call ${NLBIN##*/} $NLACT"
alias logexit="'$NLDIR'/log exit ${NLBIN##*/} $NLACT"

# set parent runlock
runlock new $NLACT $$

# check that we have something to run
[ ! -e "$NLDIR/$NLACT" ] && echo "$NLHDR
	Command does not exist.

	${NLBIN##*/} ${NLACT/./ } $@
" && exit

# run parent syncronous
logcall $@ && runexec $@ && logexit $@

# loop through actions 
for NLDO in "$NLDIR/$NLACT".*; do
	# make sure we can execute
	[ ! -x "$NLDO" ] && continue

	NLWAIT="$NLWAIT ${NLDO##*/}"

	# filter out last
	[ "${NLDO##*.}" == "last" ] && continue

	# run with locks and logging in new process
	"$NLBIN" ${NLDO##*/} $@ &
done 

# run last script after all others
[ -x "$NLDIR/$NLACT.last" ] && "$NLDIR/$NLACT.last" $@

# wait for children and finally set each runlock as finished
[ -n "$NLWAIT" ] && runlock wait 0 $NLWAIT

# set lock as done
runlock set $NLACT
