#!/bin/sh

[ -z "$1" ] && echo "$NLHDR
	Enable a Nanolin command.

    Usage:

	${NLBIN##*/} enable <command>

    Available Commands:

$(busybox find $NLDIR -type f ! -perm +111 | sed "s%$NLDIR/%\t%g" | sort)
" && exit

chmod +x "$NLDIR/$(basename "$1")"
