#!/bin/sh

[ -z "$1" ] && echo "$NLHDR
	Enable a Nanolin command.

	Usage:

	nanolin enable <command>

	Available Commands:

$(find $NLDIR -type f ! -perm +111 | sed "s%$NLDIR/%\t%g" | sort)
" && exit

chmod +x /etc/nanolin.d/$(basename "$1")
