#!/bin/sh

[ -z "$1" ] && echo "$NLHDR
	Shows the value of kernel boot flags.

	Usage:

	${NLBIN##*/} kernel <flag>
" && exit

eval "$(sed 's/\(^\|\s\)\(\w[-_a-zA-Z0-9]\+\w\)\(\s\|$\)/\1\2=true\3/g' /proc/cmdline)"
eval "echo \$$1"
