#!/bin/sh

alias runlock="$0"

ACT="$1"
LOCK="$2"
TIME="$3"

shift
shift

[ -z "$LOCK" ] && echo "$NLHDR

	Handle runlock conditions.

	Usage:
	
	${NLBIN##*/} lock new <lock> [values]
	${NLBIN##*/} lock set <lock> [values]
	${NLBIN##*/} lock add <lock> [values]
	${NLBIN##*/} lock get <lock> [waittime]
	${NLBIN##*/} lock del <lock>
	${NLBIN##*/} lock has <lock>
	${NLBIN##*/} lock not <lock>
	${NLBIN##*/} lock wait <lock>
	${NLBIN##*/} lock time <lock>
" && exit

export NLRLK="${NLRLK:-/run/lock}"

RUNLOCK="$NLRLK/${NLBIN##*/}-$LOCK.$USER"

pidwait() {
	[ -z "$1" ] && return

	for PID in $@; do
		while kill -0 $PID &>/dev/null; do
			usleep 5000
		done
	done
}

# case for various modes
case "$ACT" in
	new) echo $@ > "$RUNLOCK";;
	set) [ -e "$RUNLOCK" ] && echo $@ > "$RUNLOCK";;
	add) [ -e "$RUNLOCK" ] && echo $@ >> "$RUNLOCK";;
	get)
		CNT=$((20 * ${TIME:-0}))

		while [ ! -e "$RUNLOCK" ]; do
			[ $((CNT--)) -le 0 ] && break

			usleep 50000
		done

		[ -e "$RUNLOCK" ] && cat "$RUNLOCK";;
	del) [ -e "$RUNLOCK" ] && rm "$RUNLOCK";;
	has) [ -e "$RUNLOCK" ]; exit $?;;
	not) [ ! -e "$RUNLOCK" ]; exit $?;;
	wait)
		TIME=$LOCK

		for LOCK in $@; do
			pidwait $(runlock get $LOCK ${TIME:-20})
		done;;
	time) [ -e "$RUNLOCK" ] && stat -c %y "$RUNLOCK";;
	*) echo "$NLHDR
	Not a valid runlock action.
	" && exit;;
esac
