#!/bin/sh

export NLLOG="${NLLOG:-/var/log/$NLCLI}"

[ -z "$1" ] && echo "$NLHDR
    Usage:

	$NLCLI ${NLACT/./ } <action> [note]

    Show Log:

	$NLCLI ${NLACT/./ } show <count>
" && exit

[ ! -e /proc/uptime ] && exit

ACT=$1
TIME=$(awk '{print $1}' /proc/uptime)

shift

[ "$ACT" == "show" ] && if [ "$2" -gt "0" ] > /dev/null; then
	less "$NLLOG"
else
	tail -$2 "$NLLOG"
fi && exit

echo -e "$TIME\t$USER\t[$ACT]\t$@" >> "$NLLOG"
