#!/bin/sh

export NLLOG="${NLLOG:-/var/log/${NLBIN##*/}}"

[ -z "$1" ] && echo "$NLHDR
    Usage:

	${NLBIN##*/} logtime <action> [note]

Nanolin run log since boot:
$(cat "$NLLOG")
" && exit

[ ! -e /proc/uptime ] && exit

ACT=$1
TIME=$(awk '{print $1}' /proc/uptime)

shift

echo -e "$TIME\t$USER\t[$ACT]\t$@" >> "$NLLOG"
