#!/bin/sh

[ -n "$NLDBG" ] && echo "DEBUG: $0 $@"

#runs things only one
alias runlock="$NLDIR/lock"

# usage check 
[ -z "$1" ] && echo "$NLHDR
	Run an action only once

    Usage:

	$NLCLI ${NLACT/./ } <action> [options]
" && exit 1

# check to see whether it was run previously
runlock has $1 && echo "$NLHDR
	$NLCLI $1

Was run previously at $(runlock time $1)
" && exit 1

# run since a lock does not exist
"$NLBIN" $@
